name: mi_imperio
description: "Mi Imperio — App de educación financiera gamificada para LSF"
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  audioplayers: ^6.0.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  fl_chart: ^0.68.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  flutter_tts: ^4.0.2
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
